name: build
on: 
  push:
    branches:
      - main
jobs:
  test:
    run-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependenies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependenies
        run: npm ci
      - name: Build website
        run: npm npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
  
