name: build
on: 
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependenies
        run: npm ci
      - name: Test code
        run: npm test
      - name: Build code
        run: npm build
      - name: Deploy project
        run: echo "Deploying..."

  
